name: Golang CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify Dependencies
        working-directory: ./
        run: go mod verify

    - name: Go Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
